### ISSUE TITLE
Audio not working on Samsung Chromebook 4 | Intel Gemini lake

### ISSUE THREAD

**Issue by kylar-b** [eupnea-linux/audio-scripts#22]
When running `setup-audio` it gives the output: 

```
Traceback (most recent call last):
  File "/usr/local/bin/setup-audio", line 267, in <module>
    sof_audio("glk", user_id)
  File "/usr/local/bin/setup-audio", line 46, in sof_audio
    install_package("linux-firmware", "firmware-linux-free firmware-linux-nonfree", "linux-firmware")
  File "/usr/local/bin/setup-audio", line 167, in install_package
    bash(f"pacman -S --noconfirm --needed --reinstall {arch_package}")
  File "/usr/local/bin/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pacman -S --noconfirm --needed --reinstall linux-firmware' returned non-zero exit status 1.
```

**Comment by WeirdTreeThing** [comment]
What happens if you manually run `pacman -S --noconfirm --needed --reinstall linux-firmware`.

**Comment by Apacelus** [comment]
Fixed in https://github.com/eupnea-linux/audio-scripts/commit/b36e6e80e2105fb4626b0a4c68f252be5279cd68

**Comment by kylar-b** [comment]
It worked! Thank you.
