### ISSUE TITLE
FileNotFoundError: No such directory: /etc/eupnea/audio/sof/ucms/hdmi-common

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [eupnea-linux/audio-scripts#42]
Device: Lenovo 500e Chromebook
OS: Ubuntu 22.04.2 LTS
Kernel: Mainline
```
rajas@coral:~$ setup-audio
[sudo] password for rajas: 
Couldn't remove non existent directory: /tmp/eupnea-audio, ignoring
WARNING: this audio script is not fully functional yet!
Apollolake has two audio drivers:
SOF: Stable but doesn't work with headphones or mic.
AVS: Unstable and can cause damage to speakers but supports all audio hardware.
NOTE: Speakers are disabled on AVS as a safety precaution. Your speakers will still work on SOF though.
Which driver would you like to use? [sof/avs]: sof
Using sof
Installing SOF
Traceback (most recent call last):
  File "/usr/bin/setup-audio", line 454, in <module>
    apl_audio(device_board, user_id)
  File "/usr/bin/setup-audio", line 106, in apl_audio
    sof_audio("apl")
  File "/usr/bin/setup-audio", line 175, in sof_audio
    cpdir(f"{config_path}/audio/sof/ucms/hdmi-common", "/usr/share/alsa/ucm2/conf.d/hdmi-common")
  File "/usr/lib/eupnea/functions.py", line 99, in cpdir
    raise FileNotFoundError(f"No such directory: {src_as_path.absolute().as_posix()}")
FileNotFoundError: No such directory: /etc/eupnea/audio/sof/ucms/hdmi-common
```

Also in the logs idk if this is related but I noticed this:
```
!!PCI Soundcards installed in the system
!!--------------------------------------

00:0e.0 Multimedia audio controller [0401]: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster [8086:5a98] (rev 0b)
	Subsystem: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster [8086:7270]
```
my CPU is `Intel Celeron N3450` and it's not in the logs.

Logs: 
[alsa-info.log](https://github.com/eupnea-linux/audio-scripts/files/11045428/alsa-info.log)

**Comment by WeirdTreeThing** [comment]
Make sure your system is fully up to date.

**Comment by Apacelus** [comment]
@WeirdTreeThing you added that line pretty recently, its not in the repos yet

@ChocolateLoverRaj try again in ~4-6 hours

**Comment by WeirdTreeThing** [comment]
@Apacelus I added both the copy line in the script and the copy line in the workflow at the same time.

**Comment by Apacelus** [comment]
@WeirdTreeThing the eupnea-utils packages are not built in this repo

**Comment by WeirdTreeThing** [comment]
@ChocolateLoverRaj update your system and try again and let me know if it works now.

**Comment by ChocolateLoverRaj** [comment]
I think the last time I ran setup audio this error didn't happen.
